### ISSUE TITLE
Role value and description

### ISSUE THREAD

**Issue by ocraton** [micc83/rooles#1]
Where i can specify name and description for roles? 
I neeed to show the name with 
`Auth::user()->role->name()`
I've for example 

'admin1' = 'Administrator one'
'admin2' = 'Administrator two'

and so on.

I try to add attribute name in rooles.php but nothing seems to have happened
`
        'admin1' => [
            'name' => 'Administrator one',
            'grant' => '*'
        ],
`
thanks

**Comment by micc83** [comment]
Hello @ocraton, in version v1.0.0 it's not possible to assign a name differing from the id. Next week I'll push to dev-master the ability to pick a different name (it will then go in stable v1.1.0). The config API should work indeed using a name key inside the role array. Thank you for opening the issue.
