### ISSUE TITLE
how to get role id in blade

### ISSUE THREAD

**Issue by sombodi** [micc83/rooles#2]
Hi, thanks for the excelent code. I can't seem to be able to get the id in blade. if i use Auth::user()->role; i get the name not the id.
If i turn of getRoleAttribute in the trait i can get the ID but that obviously is not a good solution. 
Help! Thanks

**Comment by micc83** [comment]
Hello noubody,

In order to get the user role Id you can use the id() method as follow:

```
Auth::user()->role->id()
```

However if you're trying to check if a user has a given role Id you can
also:

```
If (Auth::user()->role->is('admin') ) {
    // Do something
}
```

**Comment by sombodi** [comment]
thanks!

**Comment by micc83** [comment]
You're welcome :smile:
